
spring:
  application:
    name: UserDetailService
  datasource:
    url: jdbc:h2:mem:testdb_user
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

external-service:
  user-service: http://userservice/users
  address-service: http://addressservice/addresses