
spring:
  application:
    name: UserService
  datasource:
    url: jdbc:h2:mem:testdb_user
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8085
servlet:
  contextPath: /user/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostName: localhost
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
